Telemetry server
fsherratt/upgraded-parakeet pull request #48
Opened 2020-09-29 20:47 UTC by fsherratt

2020-10-01 21:34 UTC, fsherratt commented
The server is currently set up so that it will route messages back at its self `socket_io 🠖 rabbit-MQ 🠖 UDP loopback 🠖 rabbit-MQ 🠖 socket_io`

2020-12-13 18:52 UTC, Neoxas requested changes
Please for the love of god log some error. Dump them to a file or console. Just anywhere we can trace what is going wrong

2020-12-13 18:52 UTC, Neoxas commented on modules/udp_bridge.py
> +            return  # TODO: Err here
Simple todo, plz fix. Silent errors make me cry.

2020-12-13 18:52 UTC, Neoxas commented on modules/udp_bridge.py
> +                # TODO: Log that meesage couldn't be decoded
Add a console write? Something so we can see an error

2020-12-13 18:52 UTC, Neoxas commented on modules/udp_bridge.py
> +            if msg is None:
What is the point in the continue? Sure this should be an if else?

2020-12-13 18:52 UTC, Neoxas commented on modules/udp_bridge.py
> +            # TODO: log error
Plz console.writeline

2020-12-13 18:52 UTC, Neoxas commented on modules/utils/async_message.py
> +            pass  # Silently drop message for the moment
Plz can we add something? Surely Console.log is good enough at this point?

2020-12-13 18:52 UTC, Neoxas commented on modules/utils/udp.py
> +            # TODO: Do something more helpful
Plz write failures or this will be a pain

2020-12-13 18:52 UTC, Neoxas commented on modules/utils/udp.py
> +            return
Do we really want to return silently if we are not connected?

2020-12-13 18:52 UTC, Neoxas commented on modules/utils/udp.py
> +            # TODO: something more useful here
Probably should log we a dropping events

2020-12-13 18:52 UTC, Neoxas commented on modules/utils/udp.py
> +            # TODO: something more useful here
Log timeout event

2020-12-13 18:52 UTC, Neoxas commented on server/server.py
> +        flask_secret_key="secret!",
top key. 10/10/

2021-03-13 15:12 UTC, closed without merging